CreateCaseTest, pages, models, elements, utils are added
AnnaKasyan/Qase.io_Selenide_Tests pull request #1
Opened 2021-12-27 00:14 UTC by AnnaKasyan

2022-01-05 09:03 UTC, voropa requested changes

2022-01-05 09:03 UTC, voropa commented on src/test/java/elements/Dropdown.java
> +        SelenideElement option = $(byXpath(String.format(dropdownElementLocator, label)));
Selenide позволяет написать эти действия в одну цепочку: $().click().setValue().pressEnter() и тем самым сократить количество строчек кода с 3х до одной)

2022-01-05 09:03 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +        open(baseUrl+"/login");
Можно не добавлять "baseUrl + ", а просто указывать необходимый (относительный) URL. Selenide сам добавит тк нему baseUrl

2022-01-05 09:03 UTC, voropa commented on src/test/java/tests/CreateCaseTest.java
> +        projectsPage.chooseProject();
Некорректно используешь тестовые данные. В данном конкретном случае все работает, так как метод TestDataHelper.getTestCaseData() всегда возвращает одинаковый обьект. НО, в реальной жизни TestDataHelper'ы обычно генерируют обьекты с рандомными полями. Исходя их этого методы TestDataHelper.getTestCaseData() в строчках 33 и 39 будут генерировать разные обьекты, которые никогда не будут equals.
Поэтому в начале теста нужно создать локальную переменную, точнее обьект с тестовыми данными, который будет использоваться для заполнения формы и сравнения в конце теста:
TestCase **testCase** = TestDataHelper.getTestCaseData();
...
page.fillForm(**testCase**);
....
assertEquals(actualDetailsTestCase, **testCase**);

Т.е. на протяжении всего теста мы работает с одним и тем же  обьектом, который подготовили заранее.  По такому принципу должны строится все тесты.

2022-01-05 09:03 UTC, voropa commented on src/test/java/models/TestCase.java
> +    public TestCase(String title, String description, String pre_conditions, String post_conditions, String suite, String severity, String priority, String type) {
Этот конструктор можно удалить, так как он не используется. А обьект TestCase в тестах создается через builder()

2022-01-05 12:58 UTC, AnnaKasyan commented on src/test/java/models/TestCase.java
> +    public TestCase(String title, String description, String pre_conditions, String post_conditions, String suite, String severity, String priority, String type) {
Когда я удаляю конструктор, на этапе Build возникает такая ошибка:

java: constructor TestCase in class models.TestCase cannot be applied to given types;
  required: no arguments
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length

2022-01-05 17:19 UTC, voropa commented on src/test/java/models/TestCase.java
> +    public TestCase(String title, String description, String pre_conditions, String post_conditions, String suite, String severity, String priority, String type) {
Это баг lombok'a, нагуглил, что начиная с версии 1.16.* есть такая пролема. Самый простой способ ее решения - добавить в класс оба конструктора с помощью аннотаций 
@AllArgsConstructor
@NoArgsConstructor

2022-01-06 10:26 UTC, AnnaKasyan commented on src/test/java/models/TestCase.java
> +    public TestCase(String title, String description, String pre_conditions, String post_conditions, String suite, String severity, String priority, String type) {
Спасибо!

2022-01-06 10:28 UTC, voropa approved these changes

2022-01-09 13:35 UTC, merged